### PR TITLE
Feliz Integration

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Via the [svelte-adapter/react](https://github.com/pngwn/svelte-adapter) package which provides a HOC that is automatically applied when using the `[<SvelteComponent>]` plugin 😁 

I have downgraded a couple of packages to FSharp.Core v4.7.2 because using >= 5.0.0 breaks backward-compat with many Feliz packages, also added femto metadata to the main Fable.Svelte package. I wanted to add those to `Feliz.Svelte` but since it only contains the plugin, embedding just the project file failed and Fable couldn't compile the application

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
This is great @Zaid-Ajaj, thanks a lot! Didn't know one could do `<PackageReference Update=` 😅

**Comment by alfonsogarciacaro** [comment]
@Zaid-Ajaj I'm getting this error when trying to run the FelizSvelte sample 😕 

```
alfonso@Alfonsos-MacBook-Pro ~/D/F/s/FelizSvelte (main)> npm start

> @ start /Users/alfonso/Documents/Fable.Svelte/samples/FelizSvelte
> dotnet fable watch src --exclude Fable.SveltePlugins --run webpack serve --content-base public

Fable: F# to JS compiler 3.0.1
Thanks to the contributor! @cloudRoutine
src> dotnet restore FelizSvelte.fsproj
  Determining projects to restore...
/Users/alfonso/Documents/Fable.Svelte/samples/FelizSvelte/src/FelizSvelte.fsproj : error NU1102: Unable to find package Feliz with version (>= 1.28.0)
/Users/alfonso/Documents/Fable.Svelte/samples/FelizSvelte/src/FelizSvelte.fsproj : error NU1102:   - Found 141 version(s) in nuget.org [ Nearest version: 1.22.0 ]
  Failed to restore /Users/alfonso/Documents/Fable.Svelte/samples/FelizSvelte/src/FelizSvelte.fsproj (in 1.05 sec).
  2 of 3 projects are up-to-date for restore.
```

**Comment by Zaid-Ajaj** [comment]
That's interesting because [Feliz v1.28](https://www.nuget.org/packages/Feliz) is available on nuget. Maybe you need to tell dotnet that want to use the latest v3 index to look for the package using [Nuget.Config](https://github.com/Zaid-Ajaj/Feliz/blob/master/Nuget.Config)?

**Comment by alfonsogarciacaro** [comment]
I should have checked that, sorry! It worked after clearing the Nuget cache `dotnet nuget locals --clear all`, this is great!

**Comment by Zaid-Ajaj** [comment]
Awesome! Glad you got it working :smile: would be great to push a nuget package and publish the samples into github pages

> I think I will push a new version of Feliz.Svelte which includes the `svelte-adapter` npm dependency (i.e. femto metadata) because maybe it doesn't make a lot of sense to put it in Fable.Svelte

**Pull request merged**
